version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: eshop
      POSTGRES_USER: eshop
      POSTGRES_PASSWORD: eshop
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    command: ["redis-server", "--save", "", "--appendonly", "no"]
  app:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/eshop
      - SPRING_DATASOURCE_USERNAME=eshop
      - SPRING_DATASOURCE_PASSWORD=eshop
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - JWT_SECRET=change_me
    ports:
      - 8080:8080
volumes:
  pgdata: {}
