CREATE TABLE IF NOT EXISTS notifications (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 event_id UUID NOT NULL CONSTRAINT notification_event_unique UNIQUE, user_id BIGINT NOT NULL,
 type VARCHAR(40) NOT NULL, title VARCHAR(120) NOT NULL, message VARCHAR(500) NOT NULL,
 resource_type VARCHAR(40) NOT NULL, resource_id VARCHAR(100), request_id VARCHAR(128) NOT NULL,
 trace_id VARCHAR(32), ai_execution_id UUID, status VARCHAR(16) NOT NULL, email_status VARCHAR(16) NOT NULL,
 email_attempts INTEGER NOT NULL, next_email_attempt_at TIMESTAMPTZ, emailed_at TIMESTAMPTZ,
 read_at TIMESTAMPTZ, sent_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS notification_owner_time ON notifications(user_id,created_at);
CREATE INDEX IF NOT EXISTS notification_owner_read ON notifications(user_id,read_at);
CREATE INDEX IF NOT EXISTS notification_request ON notifications(request_id);
CREATE INDEX IF NOT EXISTS notification_email_due ON notifications(email_status,next_email_attempt_at);
CREATE TABLE IF NOT EXISTS notification_preferences (user_id BIGINT PRIMARY KEY, ai_email BOOLEAN NOT NULL);
