# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://dpg-d67tvei48b3s73a9c4hg-a.oregon-postgres.render.com:5432/senghour369
spring.datasource.username=senghour
spring.datasource.password=lWQfJNJ1OH0Dx7Z7RNRbflgTBjrbaiHS
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection pool settings (optional but recommended)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
#
 #JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.javax.persistence.validation.mode=auto

# JWT
jwt.url=/authorization
jwt.header=Authorization
jwt.prefix=Bearer
jwt.expiration=12000
jwt.secret=66546A5744444446E5A7234743777217A25432A462D4A614E645267556B587032733576

# Server
server.port=8080

 #swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
 #Logging
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=DEBUG

 #Make sure these paths are completely public
springdoc.show-actuator=false
springdoc.use-management-port=false

cloudinary.cloud_name=dr9z2x9s1
cloudinary.api_key=647172284186222
cloudinary.api_secret=qpwO-rP5bQg8rc6GfYyDzrgejfQ

#
#spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
#spring.datasource.username=postgres
#spring.datasource.password=12
#spring.datasource.driver-class-name=org.postgresql.Driver
##
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.javax.persistence.validation.mode=auto
#
#server.port=8083