spring:
  application:
    name: learning-spring-security

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    display-request-duration: true
    deep-linking: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
    doc-expansion: list
    tagsSorter: alpha
    show-extensions: true
    show-common-extensions: true
  packages-to-scan:
    - com.example.learning_spring_security.controller
  paths-to-match:
    - /api/v1/**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  port: 8080