# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://dpg-d67tvei48b3s73a9c4hg-a.oregon-postgres.render.com:5432/senghour369
spring.datasource.username=senghour
spring.datasource.password=lWQfJNJ1OH0Dx7Z7RNRbflgTBjrbaiHS
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection pool settings (optional but recommended)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.javax.persistence.validation.mode=auto

# JWT
jwt.url=/authorization
jwt.header=Authorization
jwt.prefix=Bearer
jwt.expiration=120
jwt.secret=66546A5744444446E5A7234743777217A25432A462D4A614E645267556B587032733576

# Server
server.port=8080