-- Apply to each domain service database before deploying the new application.
BEGIN;
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(128), trace_id VARCHAR(128), actor_id VARCHAR(128),
    actor_type VARCHAR(32) NOT NULL, action VARCHAR(64) NOT NULL,
    resource_type VARCHAR(64) NOT NULL, resource_id VARCHAR(128), description VARCHAR(256),
    old_value JSONB, new_value JSONB, ip_address VARCHAR(64), user_agent VARCHAR(512),
    service_name VARCHAR(128) NOT NULL, result VARCHAR(16) NOT NULL,
    error_code VARCHAR(64), occurred_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_request ON audit_logs(request_id);
CREATE INDEX IF NOT EXISTS idx_audit_trace ON audit_logs(trace_id);
CREATE INDEX IF NOT EXISTS idx_audit_actor_time ON audit_logs(actor_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_audit_resource ON audit_logs(resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_audit_time ON audit_logs(occurred_at, id);
-- Separate migration owner from the application role; grant the latter SELECT/INSERT only.
-- Grant USAGE on audit_logs_id_seq to that application role.
CREATE OR REPLACE FUNCTION reject_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Audit records are append-only';
END;
$$;
DROP TRIGGER IF EXISTS audit_logs_immutable ON audit_logs;
CREATE TRIGGER audit_logs_immutable BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION reject_audit_mutation();
COMMIT;
