package com.example.eshop.common.audit;
public enum AuditAction {
    CREATE, UPDATE, DELETE, ENABLE, DISABLE, LOGIN, LOGIN_FAILED, LOGOUT, ACCESS_DENIED,
    PASSWORD_CHANGE, PASSWORD_RESET, ROLE_GRANTED, ROLE_REVOKED,
    PROMOTION_CREATE, PROMOTION_UPDATE, PROMOTION_ACTIVATE, PROMOTION_SCHEDULE,
    PROMOTION_DISABLE, PROMOTION_EXPIRE, PROMOTION_SKU_ADD, PROMOTION_SKU_REMOVE,
    PRODUCT_CREATE, PRODUCT_UPDATE, PRODUCT_DISABLE, SKU_CREATE, SKU_UPDATE, SKU_DELETE,
    CATEGORY_CREATE, CATEGORY_UPDATE, CATEGORY_DELETE, INVENTORY_ADJUST, ORDER_CANCEL, PAYMENT_REFUND
}
