-- Run once against the EXISTING catalog database before deploying this release.
-- Existing Hibernate-managed tables must already exist. Stop writers during upgrade.
BEGIN;
CREATE TABLE promotions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL CHECK (length(trim(name)) > 0),
    code varchar(60) UNIQUE, description varchar(2000),
    promotion_type varchar(40) NOT NULL CHECK (promotion_type IN ('PRODUCT_DISCOUNT','FLASH_SALE','SEASONAL_SALE')),
    discount_type varchar(30) NOT NULL CHECK (discount_type IN ('PERCENTAGE','FIXED_AMOUNT')),
    discount_value numeric(19,4) NOT NULL CHECK (discount_value > 0),
    max_discount_amount numeric(19,2) CHECK (max_discount_amount >= 0),
    minimum_order_amount numeric(19,2) CHECK (minimum_order_amount >= 0),
    start_at timestamp NOT NULL, end_at timestamp NOT NULL CHECK (end_at > start_at),
    status varchar(20) NOT NULL CHECK (status IN ('DRAFT','SCHEDULED','ACTIVE','EXPIRED','DISABLED')),
    priority integer NOT NULL DEFAULT 0,
    usage_limit bigint CHECK (usage_limit >= 0),
    usage_per_customer bigint CHECK (usage_per_customer >= 0),
    stackable boolean NOT NULL DEFAULT false CHECK (stackable = false),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp, updated_at timestamp, deleted_at timestamp,
    created_by varchar(255), updated_by varchar(255),
    CHECK (discount_type <> 'PERCENTAGE' OR discount_value <= 100)
);
CREATE INDEX ix_promotion_window ON promotions(status,is_active,start_at,end_at);
CREATE TABLE promotion_skus (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id bigint NOT NULL REFERENCES promotions(id),
    product_sku_id bigint NOT NULL REFERENCES product_skus(id),
    created_at timestamp, updated_at timestamp, deleted_at timestamp,
    CONSTRAINT uk_promotion_sku UNIQUE(promotion_id,product_sku_id)
);
CREATE INDEX ix_promotion_sku_lookup ON promotion_skus(product_sku_id,promotion_id);
CREATE TABLE checkout_reservations (
    order_id bigint PRIMARY KEY, user_id bigint NOT NULL,
    status varchar(255) NOT NULL CHECK (status IN ('RESERVED','CONFIRMED','RELEASED')),
    snapshot text NOT NULL,
    created_at timestamp, updated_at timestamp, deleted_at timestamp
);
CREATE TABLE promotion_usages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id bigint NOT NULL REFERENCES promotions(id),
    user_id bigint NOT NULL, order_id bigint NOT NULL,
    discount_amount numeric(19,2) NOT NULL CHECK (discount_amount >= 0),
    used_at timestamp NOT NULL, released boolean NOT NULL DEFAULT false,
    CONSTRAINT uk_promotion_order UNIQUE(promotion_id,order_id)
);
CREATE INDEX ix_usage_customer ON promotion_usages(promotion_id,user_id,released);
CREATE INDEX ix_usage_order ON promotion_usages(order_id);
-- Existing services assume exactly one inventory record per SKU.
-- Duplicate SKU rows or invalid stock cause the transaction to fail: resolve them explicitly.
ALTER TABLE inventories ADD COLUMN version bigint NOT NULL DEFAULT 0;
ALTER TABLE inventories ADD CONSTRAINT uk_inventory_sku UNIQUE(product_sku_id);
ALTER TABLE inventories ADD CONSTRAINT ck_inventory_quantities CHECK (
    quantity >= 0 AND reserved_quantity >= 0 AND reserved_quantity <= quantity
);
UPDATE inventories SET available_quantity = quantity - reserved_quantity;
ALTER TABLE inventories ADD CONSTRAINT ck_inventory_available CHECK (available_quantity = quantity - reserved_quantity);
COMMIT;
