server:
  forward-headers-strategy: none
  port: 8087

spring:
  application:
    name: admin-service
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5439/admin_db}
    username: ${DATABASE_USERNAME:senghour}
    password: ${DATABASE_PASSWORD:senghour369}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 1s
      connect-timeout: 1s
      repositories:
        enabled: false

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSSXXX} %-5level service=admin-service requestId=%X{requestId:-} traceId=%X{traceId:-} spanId=%X{spanId:-} [%thread] %logger{36} - %msg%n"

admin:
  monitor-enabled: true
  monitor-delay-ms: 30000
  monitor-retention: PT24H

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
