-- Expand Hibernate-created checks to the current Java enums. No rows are removed.
BEGIN;
SET LOCAL lock_timeout = '5s';
ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS audit_logs_action_check;
ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_action_check CHECK (action IN ('AI_REQUEST_ACCEPTED', 'AI_TOOL_EXECUTION', 'CREATE', 'UPDATE', 'DELETE', 'ENABLE', 'DISABLE', 'LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'ACCESS_DENIED', 'PASSWORD_CHANGE', 'PASSWORD_RESET', 'ROLE_GRANTED', 'ROLE_REVOKED', 'PROMOTION_CREATE', 'PROMOTION_UPDATE', 'PROMOTION_ACTIVATE', 'PROMOTION_SCHEDULE', 'PROMOTION_DISABLE', 'PROMOTION_EXPIRE', 'PROMOTION_SKU_ADD', 'PROMOTION_SKU_REMOVE', 'PRODUCT_CREATE', 'PRODUCT_UPDATE', 'PRODUCT_DISABLE', 'SKU_CREATE', 'SKU_UPDATE', 'SKU_DELETE', 'CATEGORY_CREATE', 'CATEGORY_UPDATE', 'CATEGORY_DELETE', 'INVENTORY_ADJUST', 'ORDER_CANCEL', 'PAYMENT_REFUND'));
ALTER TABLE ai_executions DROP CONSTRAINT IF EXISTS ai_executions_intent_check;
ALTER TABLE ai_executions ADD CONSTRAINT ai_executions_intent_check CHECK (intent IN ('PRODUCT_GET', 'KNOWLEDGE_SEARCH', 'PRODUCT_SEARCH', 'SKU_GET', 'INVENTORY_GET', 'INVENTORY_LOW_STOCK', 'ORDER_GET', 'MY_ORDERS', 'MY_ORDER_STATUS', 'MY_PAYMENT_STATUS', 'MY_RETURNS', 'MY_NOTIFICATIONS', 'ADMIN_ORDER_LIST', 'ADMIN_PAYMENT_LIST', 'ADMIN_RETURN_LIST', 'ADMIN_ORDER_SUMMARY', 'ADMIN_USER_LIST', 'ADMIN_REVENUE_SUMMARY', 'ADMIN_AUDIT_LOG', 'PROMOTION_GET', 'PROMOTION_CREATE', 'PROMOTION_DISABLE', 'ORDER_CANCEL', 'PAYMENT_REFUND', 'ROLE_GRANT', 'UNKNOWN'));
COMMIT;

